---
- name: Load OS-specific vars.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - main.yml
      paths:
        - 'vars'

- name: Create users and groups
  ansible.builtin.import_tasks: create.yml

- name: Delete users and groups
  ansible.builtin.import_tasks: delete.yml
...
